from typing import Union, Iterable, Iterator

def int2byte(character: int) -> bytes: ...
def byte2int(character: bytes) -> int: ...
def str2bytes(string: str) -> bytes: ...
def bytes2str(string: bytes) -> str: ...
def iteratebytes(data: bytes) -> Iterator[bytes]: ...
def iterateints(data: bytes) -> Iterator[int]: ...
def reprstring(data: Union[bytes, str]) -> str: ...
def trimstring(data: Union[bytes, str]) -> str: ...
def integers2bytes(ints: Iterable[int]) -> bytes: ...
def bytes2integers(data: bytes) -> list[int]: ...
